namespace BODA.VMS.MLOps.Tests.TestAssets;

/// <summary>
/// 스텁 ONNX — VMS 리포 VMS.Core.Tests/DetectionModelFormatProbeTests.cs 와 동일 자산 (8 쿼리·2 클래스 상수 그래프).
/// 규약 계약 테스트(개발 문서 §11)용. 세션 생성 없이 protobuf 만 읽는다.
/// </summary>
public static class OnnxStubs
{
    /// <summary>D-FINE deploy 규약 + metadata_props(names/imgsz/model_format=dfine)</summary>
    public const string DeployWithMeta =
        "CAg61AYKLQoRb3JpZ190YXJnZXRfc2l6ZXMSB3NpemVzX2YiBENhc3QqCQoCdG8YAaABAgpMEgRnaWR4IghDb25zdGFudCo6CgV2YWx1ZSouCAQQB0IGZ2lkeF92SiABAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAKABBAoqCgdzaXplc19mCgRnaWR4EgR3aHdoIgZHYXRoZXIqCwoEYXhpcxgBoAECCjISA3VheCIIQ29uc3RhbnQqIQoFdmFsdWUqFQgBEAdCBXVheF92SggBAAAAAAAAAKABBAodCgR3aHdoCgN1YXgSBXdod2gzIglVbnNxdWVlemUKvwESCmJveGVzX25vcm0iCENvbnN0YW50KqYBCgV2YWx1ZSqZAQgBCAgIBBABQgxib3hlc19ub3JtX3ZKgAHNzMw9zcxMPgAAAD+amRk/AAAAPwAAAD9mZmY/ZmZmP65H4T09Clc+XI8CP/YoHD8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKABBAofCgpib3hlc19ub3JtCgV3aHdoMxIFYm94ZXMiA011bApyEgZsYWJlbHMiCENvbnN0YW50Kl4KBXZhbHVlKlIIAQgIEAdCCGxhYmVsc192SkABAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAoAEEClISBnNjb3JlcyIIQ29uc3RhbnQqPgoFdmFsdWUqMggBCAgQAUIIc2NvcmVzX3ZKIGZmZj+amRk/AAAAPwAAAAAAAAAAAAAAAAAAAAAAAAAAoAEEEhFkZmluZV9kZXBsb3lfc3R1YloiCgZpbWFnZXMSGAoWCAESEgoCCAEKAggDCgMIgAUKAwiABVojChFvcmlnX3RhcmdldF9zaXplcxIOCgwIBxIICgIIAQoCCAJiGAoGbGFiZWxzEg4KDAgHEggKAggBCgIICGIbCgVib3hlcxISChAIARIMCgIIAQoCCAgKAggEYhgKBnNjb3JlcxIOCgwIARIICgIIAQoCCAhCBAoAEA1yIQoFbmFtZXMSGHswOiAnZ29vZCcsIDE6ICdkZWZlY3QnfXITCgVpbWdzehIKWzY0MCwgNjQwXXIVCgxtb2RlbF9mb3JtYXQSBWRmaW5l";

    /// <summary>D-FINE deploy 규약, 메타데이터 없음 (그래프 입출력 이름으로만 판별)</summary>
    public const string DeployNoMeta =
        "CAg61AYKLQoRb3JpZ190YXJnZXRfc2l6ZXMSB3NpemVzX2YiBENhc3QqCQoCdG8YAaABAgpMEgRnaWR4IghDb25zdGFudCo6CgV2YWx1ZSouCAQQB0IGZ2lkeF92SiABAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAKABBAoqCgdzaXplc19mCgRnaWR4EgR3aHdoIgZHYXRoZXIqCwoEYXhpcxgBoAECCjISA3VheCIIQ29uc3RhbnQqIQoFdmFsdWUqFQgBEAdCBXVheF92SggBAAAAAAAAAKABBAodCgR3aHdoCgN1YXgSBXdod2gzIglVbnNxdWVlemUKvwESCmJveGVzX25vcm0iCENvbnN0YW50KqYBCgV2YWx1ZSqZAQgBCAgIBBABQgxib3hlc19ub3JtX3ZKgAHNzMw9zcxMPgAAAD+amRk/AAAAPwAAAD9mZmY/ZmZmP65H4T09Clc+XI8CP/YoHD8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKABBAofCgpib3hlc19ub3JtCgV3aHdoMxIFYm94ZXMiA011bApyEgZsYWJlbHMiCENvbnN0YW50Kl4KBXZhbHVlKlIIAQgIEAdCCGxhYmVsc192SkABAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAoAEEClISBnNjb3JlcyIIQ29uc3RhbnQqPgoFdmFsdWUqMggBCAgQAUIIc2NvcmVzX3ZKIGZmZj+amRk/AAAAPwAAAAAAAAAAAAAAAAAAAAAAAAAAoAEEEhFkZmluZV9kZXBsb3lfc3R1YloiCgZpbWFnZXMSGAoWCAESEgoCCAEKAggDCgMIgAUKAwiABVojChFvcmlnX3RhcmdldF9zaXplcxIOCgwIBxIICgIIAQoCCAJiGAoGbGFiZWxzEg4KDAgHEggKAggBCgIICGIbCgVib3hlcxISChAIARIMCgIIAQoCCAgKAggEYhgKBnNjb3JlcxIOCgwIARIICgIIAQoCCAhCBAoAEA0=";

    /// <summary>HF 원본 규약 (pixel_values → logits/pred_boxes), names 메타만</summary>
    public const string RawHf =
        "CAg6sgMKdBIGbG9naXRzIghDb25zdGFudCpgCgV2YWx1ZSpUCAEICAgCEAFCCGxvZ2l0c192SkAAACDBVJ8MQB+Zzz4AACDBAAAgwQAAIMEAACDBAAAgwQAAIMEAACDBAAAgwQAAIMEAACDBAAAgwQAAIMEAACDBoAEECr8BEgpwcmVkX2JveGVzIghDb25zdGFudCqmAQoFdmFsdWUqmQEIAQgICAQQAUIMcHJlZF9ib3hlc192SoABmpmZPs3MzD7NzMw+zczMPjMzMz8zMzM/zczMPs3MzD4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACgAQQSDmRmaW5lX3Jhd19zdHViWigKDHBpeGVsX3ZhbHVlcxIYChYIARISCgIIAQoCCAMKAwiABQoDCIAFYhwKBmxvZ2l0cxISChAIARIMCgIIAQoCCAgKAggCYiAKCnByZWRfYm94ZXMSEgoQCAESDAoCCAEKAggICgIIBEIECgAQDXIhCgVuYW1lcxIYezA6ICdnb29kJywgMTogJ2RlZmVjdCd9";

    /// <summary>Ultralytics YOLO 규약: images[1,3,640,640] → output0[1,6,8], names 메타</summary>
    public const string YoloStub =
        "CAg6ygIK+QESB291dHB1dDAiCENvbnN0YW50KuMBCgV2YWx1ZSrWAQgBCAYICBABQglvdXRwdXQwX3ZKwAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACgAQQSCXlvbG9fc3R1YloiCgZpbWFnZXMSGAoWCAESEgoCCAEKAggDCgMIgAUKAwiABWIdCgdvdXRwdXQwEhIKEAgBEgwKAggBCgIIBgoCCAhCBAoAEA1yIQoFbmFtZXMSGHswOiAnZ29vZCcsIDE6ICdkZWZlY3QnfQ==";

    public static byte[] Bytes(string base64) => Convert.FromBase64String(base64);

    public sealed class TempOnnx : IDisposable
    {
        public string Path { get; }
        public TempOnnx(string base64, string tag = "stub")
        {
            Path = System.IO.Path.Combine(System.IO.Path.GetTempPath(), $"mlops-{tag}-{Guid.NewGuid():N}.onnx");
            File.WriteAllBytes(Path, Bytes(base64));
        }
        public void Dispose() { try { File.Delete(Path); } catch { } }
    }
}
